// <auto-generated />
namespace KarenProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class karen011 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(karen011));
        
        string IMigrationMetadata.Id
        {
            get { return "201504191054243_karen011"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
