// <auto-generated />
namespace KarenProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class karen01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(karen01));
        
        string IMigrationMetadata.Id
        {
            get { return "201504120942299_karen01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
